id = 832801421241483274
hosts = ["localhost:6600"]

[format]
details = "Title: $title | Album: $album | Genre: $genre ğŸµ"
state = "Artist: $artist | Year: $date ğŸ¤"
timestamp = "left"
large_image = "apple-music-note"
large_text = "Music"
